#!/usr/bin/env node
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const grammarPath = join(repoRoot, "grammar.js");

const require = createRequire(import.meta.url);

function installDslStubs(target) {
  const stub =
    (name) =>
    (...args) => ({ type: name, args });
  target.seq = stub("seq");
  target.choice = stub("choice");
  target.repeat = stub("repeat");
  target.repeat1 = stub("repeat1");
  target.optional = stub("optional");
  target.alias = (value, name) => ({ type: "alias", value, name });
  target.field = (name, value) => ({ type: "field", name, value });
  const token = (arg) => ({ type: "token", arg });
  token.immediate = (arg) => ({ type: "token.immediate", arg });
  target.token = token;
  const prec = (precedence, rule) => ({ type: "prec", precedence, rule });
  prec.left = (precedence, rule) => ({ type: "prec.left", precedence, rule });
  prec.right = (precedence, rule) => ({ type: "prec.right", precedence, rule });
  prec.dynamic = (precedence, rule) => ({
    type: "prec.dynamic",
    precedence,
    rule,
  });
  target.prec = prec;
  target.grammar = (spec) => spec;
}

installDslStubs(global);

if (!existsSync(grammarPath)) {
  throw new Error(`Missing grammar source at ${grammarPath}`);
}

const { foldConstants } = require("../grammar.js");
if (!foldConstants) {
  throw new Error("grammar.js does not export foldConstants");
}

const { NODES = [] } = foldConstants;

function buildFolds() {
  if (NODES.length === 0) {
    return "";
  }

  const lines = [
    ";; Auto-generated by tenzir/tree-sitter-tql/scripts/generate-folds.mjs. DO NOT EDIT.",
    "",
    "[",
    ...Array.from(new Set(NODES)).map((node) => `  (${node})`),
    "] @fold",
    "",
  ];

  return lines.join("\n");
}

function main() {
  const args = process.argv.slice(2);
  const outputs = args.length > 0
    ? args
    : [
        "languages/tql/folds.scm",
        "queries/tql/folds.scm",
      ];

  const content = buildFolds();

  for (const outputArg of outputs) {
    const outputPath = resolve(repoRoot, outputArg);
    const outputDir = dirname(outputPath);
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }
    writeFileSync(outputPath, content, "utf8");
    console.log(`Wrote ${outputPath}`);
  }
}

main();
